title: Marwan Charafeddine
logo: docs/assets/revisedLogoForGitHubPages.png
description: E-Mail: mcharafeddinedev@gmail.com | Digital Gaming & Simulation Programmer | Indie Game Developer
#show_downloads: true
theme: jekyll-theme-minimal
