title: "Marwan Charafeddine"
logo: "docs/assets/revisedLogoForGitHubPages.png"
description: |
  Game Scripting & Programming
  Independent Game Developer
  mcharafeddinedev@gmail.com
#show_downloads: true
theme: jekyll-theme-minimal
