title: Marwan Charafeddine
logo: docs/assets/revisedLogoForGitHubPages.png
description: Digital Gaming & Simulation Programmer | Indie Game Developer 
#show_downloads: true
theme: jekyll-theme-minimal
