title: "Marwan Charafeddine"
logo: "docs/assets/revisedLogoForGitHubPages.png"
description: |
  E-Mail: mcharafeddinedev@gmail.com
  Digital Gaming & Simulations Programmer
  Independent Game Developer
#show_downloads: true
theme: jekyll-theme-minimal
